changelog:
  categories:
    - title: Breaking Changes 🛠
      labels:
        - release
    - title: New Features 🎉
      labels:
        - enhancement
        - documentation
    - title: Fixes
      labels:
        - bug
        - dependencies